name: Testing ENV vars
on: push

jobs:
  cypress-e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3100'
          browser: chrome
        env:
          API_MOCKING: enabled

