name: Testing ENV vars
on: push

jobs:
  test-env:
    name: Testing ENV vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        run: bash ./index.sh
        shell: bash
        env:
          API_MOCKING: enabled

